# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MucleryiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MucleryiOS

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'GoogleDataTransport', :git=>'https://github.com/firebase/firebase-ios-sdk.git', :commit=>'38be2cc'

  target 'MucleryiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MucleryiOSUITests' do
    # Pods for testing
  end



end
